[package]
name = "rusty-mc-server"
version = "0.0.1"
authors = ["Daniel Prilik <danielprilik@gmail.com>"]
edition = "2018"

[dependencies]
base64 = "0.10.1"
serde = { version = "1.0.94", features = ["derive"] }
serde_json = "1.0.40"
uuid = { version =  "0.7.4", features = ["v4"] }
